export interface AgentModel {
  id: string;
  name: string;
  tag: string;
  badge: string;
  desc: string;
  color: string;
  symbol: string;
  verb: string;
  cta: string;
  route?: string;
  examples: { label: string; icon: string }[];
}

export const MODELS: AgentModel[] = [
  {
    id: "qws-ultra-v4",
    name: "QWS-ULTRA-V4",
    tag: "Language · Reasoning",
    badge: "DEFAULT",
    desc: "General purpose language model with advanced multi-step reasoning",
    color: "#e2e8f0",
    symbol: "◈",
    verb: "build",
    cta: "Build it",
    examples: [
      { label: "SaaS landing page",   icon: "🚀" },
      { label: "Developer portfolio", icon: "💼" },
      { label: "Analytics dashboard", icon: "📊" },
      { label: "Online store",        icon: "🛍️" },
      { label: "Restaurant website",  icon: "🍽️" },
      { label: "Pricing page",        icon: "💎" },
      { label: "Blog homepage",       icon: "✍️" },
      { label: "Personal resume",     icon: "📄" },
    ],
  },
  {
    id: "qws-vision-3",
    name: "QWS-VISION-3",
    tag: "Image · Multimodal",
    badge: "VISION",
    desc: "Image generation, visual analysis, and multimodal reasoning",
    color: "#a78bfa",
    symbol: "◉",
    verb: "design",
    cta: "Generate",
    examples: [
      { label: "Product hero image",    icon: "🖼️" },
      { label: "UI wireframe",          icon: "📐" },
      { label: "Brand mood board",      icon: "🎨" },
      { label: "Logo concept",          icon: "✦" },
      { label: "Social media banner",   icon: "📱" },
      { label: "Infographic",           icon: "📈" },
      { label: "App icon set",          icon: "🔲" },
      { label: "Website mockup",        icon: "🌐" },
    ],
  },
  {
    id: "qws-code-x",
    name: "QWS-CODE-X",
    tag: "Code · Synthesis",
    badge: "CODE",
    desc: "Code generation, debugging, and refactoring across 50+ languages",
    color: "#34d399",
    symbol: "⌘",
    verb: "code",
    cta: "Code it",
    route: "/generate",
    examples: [
      { label: "REST API in Node.js",    icon: "⚡" },
      { label: "Python scraper",         icon: "🐍" },
      { label: "React component",        icon: "⚛️" },
      { label: "SQL schema",             icon: "🗃️" },
      { label: "Authentication system",  icon: "🔐" },
      { label: "CLI tool in Go",         icon: "🖥️" },
      { label: "Data pipeline",          icon: "🔄" },
      { label: "Unit test suite",        icon: "✅" },
    ],
  },
  {
    id: "qws-audio-2",
    name: "QWS-AUDIO-2",
    tag: "Speech · Music",
    badge: "AUDIO",
    desc: "Text-to-speech synthesis and generative music composition",
    color: "#fbbf24",
    symbol: "◎",
    verb: "compose",
    cta: "Compose",
    examples: [
      { label: "Podcast intro",           icon: "🎙️" },
      { label: "Background music",        icon: "🎵" },
      { label: "Voiceover script",        icon: "📢" },
      { label: "Sound effect pack",       icon: "🔊" },
      { label: "Audiobook narration",     icon: "📖" },
      { label: "Jingle for ad",           icon: "📣" },
      { label: "Ambient study music",     icon: "🎧" },
      { label: "Alert & notification set",icon: "🔔" },
    ],
  },
  {
    id: "qws-biz-4",
    name: "QWS-BIZ-4",
    tag: "Business · Intelligence",
    badge: "BIZ",
    desc: "Business analysis, SWOT, market research, and strategic intelligence",
    color: "#22d3ee",
    symbol: "◑",
    verb: "analyze",
    cta: "Analyze",
    route: "/business",
    examples: [
      { label: "SWOT analysis",           icon: "🧩" },
      { label: "Market sizing report",    icon: "📊" },
      { label: "Competitor breakdown",    icon: "⚔️" },
      { label: "Financial projections",   icon: "💰" },
      { label: "Go-to-market strategy",   icon: "🎯" },
      { label: "Startup feasibility",     icon: "🚦" },
      { label: "Customer persona",        icon: "👤" },
      { label: "KPI dashboard plan",      icon: "📈" },
    ],
  },
  {
    id: "qws-ppt-1",
    name: "QWS-PPT-1",
    tag: "Presentation · Slides",
    badge: "PPT",
    desc: "Generate stunning PowerPoint decks from a single prompt",
    color: "#fb923c",
    symbol: "▣",
    verb: "present",
    cta: "Create Deck",
    route: "/presentation",
    examples: [
      { label: "Investor pitch deck",     icon: "💼" },
      { label: "Company overview",        icon: "🏢" },
      { label: "Product launch deck",     icon: "🚀" },
      { label: "Quarterly review",        icon: "📅" },
      { label: "Sales proposal",          icon: "🤝" },
      { label: "Research summary",        icon: "🔬" },
      { label: "Training material",       icon: "📚" },
      { label: "Strategy roadmap",        icon: "🗺️" },
    ],
  },
  {
    id: "qws-research-1",
    name: "QWS-RESEARCH-1",
    tag: "Research · Synthesis",
    badge: "RESEARCH",
    desc: "Deep research, literature synthesis, and knowledge distillation",
    color: "#e879f9",
    symbol: "◆",
    verb: "research",
    cta: "Research",
    examples: [
      { label: "AI trends 2025",          icon: "🤖" },
      { label: "Climate tech landscape",  icon: "🌍" },
      { label: "Web3 deep dive",          icon: "🔗" },
      { label: "Health tech overview",    icon: "🏥" },
      { label: "Market entry analysis",   icon: "🔍" },
      { label: "Literature review",       icon: "📜" },
      { label: "Technology comparison",   icon: "⚖️" },
      { label: "Industry forecast",       icon: "🔭" },
    ],
  },
  {
    id: "qws-data-1",
    name: "QWS-DATA-1",
    tag: "Data · Analytics",
    badge: "DATA",
    desc: "Data analysis, chart generation, and statistical modeling",
    color: "#2dd4bf",
    symbol: "◐",
    verb: "analyze",
    cta: "Analyze",
    examples: [
      { label: "Sales funnel analysis",   icon: "📉" },
      { label: "User behavior report",    icon: "👥" },
      { label: "Revenue breakdown",       icon: "💹" },
      { label: "Churn prediction model",  icon: "🔄" },
      { label: "A/B test results",        icon: "🧪" },
      { label: "Cohort analysis",         icon: "📊" },
      { label: "KPI tracker",             icon: "🎯" },
      { label: "Forecast model",          icon: "📈" },
    ],
  },
];

export const DEFAULT_MODEL = MODELS[0];
